name: newyork_times_clone_starter
description: New York Times app clone

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  photo_view: ^0.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: OldLondon
      fonts:
        - asset: assets/OldLondon.ttf
    - family: TimesNew
      fonts:
        - asset: assets/times-new-roman.ttf
    - family: NotaSerif
      fonts:
       - asset: assets/NotoSerif-Regular.ttf


  assets:
    - assets/defaultimage.png